### ISSUE TITLE
Layout decente

### ISSUE THREAD

**Issue by huichops** [huichops/simon#12]
# Scope
Además de mejorar la presentación de nuestro simón creo que valdría la pena ponerlo más cercano a la realidad, tanto en colores como en las notas que se tocan en cada botón. 

**Aunque eso sí no sé si darle un look más actual, o tratar de darle el gatazo de los 80's?**

**Comment by huichops** [comment]
@Alex-TH @beeetooo

**Comment by Alex-TH** [comment]
algo medio 80's hipster millennial :D

**Comment by aromeronavia** [comment]
Algo sencillo mae, no se ocupa mucha 100cya.
Pregúntale a @raulaguilarv

**Comment by huichops** [comment]
tranquis pero jala
