### ISSUE TITLE
audio y luz al clickear

### ISSUE THREAD

**Issue by huichops** [huichops/simon#14]
Cuando estás clickeando cada botón no hay feedback visual ni auditivo. Hay que hacer que suene cada que le das click a un botonsito :)

**Comment by aromeronavia** [comment]
Este pedo ya está, lo hizo @Alex-TH 
Voy a cerrarlo pero si me equivoco feel free to re open

**Comment by huichops** [comment]
Nel no suena, y ese hover debería ser más tranqui la reabro y yo la hago y así

**Comment by Alex-TH** [comment]
pero yo lo quiero... haz paro!

**Comment by huichops** [comment]
Nel qlo ya empecé, jálate otro jaja

**Comment by huichops** [comment]
ya
