### ISSUE TITLE
Separar State del juego de Game y board

### ISSUE THREAD

**Issue by Alex-TH** [huichops/simon#22]
Estamos teniendo una acoplacion bastante feita del state del juego con el juego en si y con el board.

Amos a abstraer este pedo:

Pseudocodigo de GameState
```javascript
import { BLINK, ADDING, LOST, PLAYING } = './constants';
import GameStatePresenter from './GameStatePresenter';

const validStates = [ BLINK, ADDING, LOST, PLAYING ];

class GameState {
  constructor() {
    this.presenter = new GameStatePresenter();
    initializeState();
  }

  changeState(state) {
    if (validStates.find(state)) {
      this.state = state;
    }
  }

  initializeState() {
    this.state =  BLINK;
    this.score = 0;
  }

  increaseScore() {
    if (this.state === PLAYING) {
      this.score += 1;
    }
  }

  presentScore() {
    this.presenter.setScore(this.score);
  }

  getState() {
    return this.state;
  }
}
```
El GameStatePresenter solo juega con el html para mostrar el score en este caso.

Que les perece?

**Comment by aromeronavia** [comment]
Tengo miedo jajaja 
Se me hace mucha complejidad eso del GameStatePresenter, porque ahora el detalle del DOM tiene dos diferentes puntos de entrada, que es el Board y el GameStatePresenter. Por qué el Board no lo podría tener?
O a lo mejor podría haber algo más grande que no sea el Board pues, pero que esa cosa use el board y el game state presenter.
Eso haría más sentido 🤔  pero no lo sé, sigamos iterando.
Olvida todo lo que dije, bullshit, tiene sentido tener todo en un solo lugar como GamePresenter y que ese dude use al board y un scorePresenter o algo así.

**Comment by aromeronavia** [comment]
Olvida todo lo que dije, bullshit, tiene sentido tener todo en un solo lugar como GamePresenter y que ese dude use al board y un scorePresenter o algo así.

**Comment by huichops** [comment]
Y si instalamos redux? Jajajaja

**Comment by aromeronavia** [comment]
Has un spec de por qué necesitamos redux, y te la valgo.

**Comment by aromeronavia** [comment]
@huichops ^

**Comment by huichops** [comment]
Oye pero que 100tifico, está bien verga responder por correo. El correo lo
es todo los bots nunca superarán esto ❤️

**Comment by aromeronavia** [comment]
JAJAJAJAJA

**Comment by Alex-TH** [comment]
jajajaja

Y si hacemos rewrite?

**Comment by huichops** [comment]
Es hermozzzoo. Al rato escribo eso redux o Rx para observables, creo que
nos ayudaría a bajarle complejidad a estos desmadres que andamos haciendo.
Aunque si, la idea era darle full vanilla ajaaaiii

**Comment by Alex-TH** [comment]
he no sean qlos, o hagamos nuestro propio publish/subscribe

**Comment by huichops** [comment]
Entonces hagamos eso mejor. Se pueden hacer observables fácil con un
generador y un while infinito o class Qlo extends EventEmitter y ya alv.
Necesitamos custom events que no dependan de los del DOM sino que sean para
el jueguito y así

**Comment by huichops** [comment]
![simon](https://user-images.githubusercontent.com/1053334/27306805-b367fef0-550c-11e7-95a4-c2db27d763de.png)

**Comment by aromeronavia** [comment]
Neta necesitamos un state machino?

**Comment by huichops** [comment]
Creo que aunque se haga con un par de if's la stateMachine ahí está. No necesitamos implementar una madre para estados como tal, estamos bien así como está ahorita :) Yo diría que close jajaja

**Comment by aromeronavia** [comment]
Close for now, pero definitely revisit when having troubles
